@startwbs
skinparam handwritten true
* iona
** iona-cluster
*** static-ip
*** router
*** cloud-nat
*** firewall-rule-ingress-80,443
*** ingress-node-pool
*** work-node-pool
*** kubeip-iam-role
** iona-cluster-k8s
*** dns01solver service account (workload identity)
*** kubeip service account (workload identity)
*** kubeip cluster role
*** envoy-lb
*** traefik (kubernetes CRD  + redis KV providers)
*** cert-manager (CRD + dns01)
*** grafana & grafana service account (workload identity)
*** grafana cluster role binding (for standard monitoring roles)
** k8s kustomize
*** wild cert for *.thaumagen.io
*** externalName: thaumagen.github.io
*** traefik routes: iona.thaumagen.io: /static, /public, /authn, /thaumagen
*** traefik route: grafana.iona.thaumagen.io
@endwbs
