@startuml
!include <kubernetes/k8s-sprites-unlabeled-25pct>
skinparam handwritten true 

frame "iona" {
component "<$ing,scale=0.25>\nstatic ip" as staticip

component "ingress-node-pool" {
  cloud "ingress-node" as ingressnode
  component "<$svc,scale=0.25>\nenvoy-lb" as envoylb
  ingressnode -> envoylb
}

staticip ..> ingressnode

component "work-node-pool" {
  component "<$svc>\niona-traefik" as ionatraefik
  component "<$svc,scale=0.25>\ncert manager" as  ionacertmanager
  component "<$svc,scale=0.25>\ngrafana" as grafana
  cloud "<$svc>\nservices" as ionanginx
  ionacertmanager -> ionatraefik
  ionatraefik -> ionanginx
  ionatraefik -> grafana
}

envoylb --> ionatraefik


cloud "private services access" as privateservicesaccess
}

cloud "letsencrypt" as lestencrypt
cloud "GitHub Pages" as githubpages

ionacertmanager ..> lestencrypt
ionatraefik ..> githubpages

frame "google services" {
  cloud "memorystore (redis)" as redis
  cloud "cloud monitoring" as gcpmonitoring
}

privateservicesaccess --> redis
grafana --> gcpmonitoring

@enduml
