http:

  services:

    # failsafe service and available as soon as traefik is up
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx.iona:80/

    # for GitHub pages use this if the ExternalName k8s service approach becomes problematic
    # thaumagen-github-io:
    #   loadBalancer:
    #     passHostHeader: false
    #     servers:
    #       - url: https://thaumagen.github.io/
