http:
  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx.iona:80/
  routers:
    iona-thaumagen-io-tls:
      entryPoints:
        - web
        - websecure
      rule: Host(`iona.thaumagen.io`) && ( PathPrefix(`/static`) || PathPrefix(`/authn`) )
      service: nginx
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
