http:
  routers:
    iona-thaumagen-io-tls:
      entryPoints:
        - web
        - websecure
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/static`)
      service: nginx
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
