http:
  middlewares:
    add-iona-prefix:
      addPrefix:
        prefix: "/iona"

  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx.iona:80/

    thaumagen-github-io:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://thaumagen.github.io/

  routers:
    iona-authn:
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/iona/authn`)
      entryPoints:
        - websecure
      # middlewares:
      #   - add-iona-prefix
      service: thaumagen-github-io
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
    iona-thaumagen-io-tls:
      entryPoints:
        - web
        - websecure
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/static`)
      service: nginx
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
