http:
  middlewares:
    add-iona-prefix:
      addPrefix:
        prefix: "/iona"

  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana.monitoring:80/
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx.iona:80/

    thaumagen-github-io:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://thaumagen.github.io/

  routers:
    iona-grafana:
      rule: Host(`grafana.iona.thaumagen.io`)
      service: grafana
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"

    iona-authn:
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/authn`)
      entryPoints:
        - websecure
      middlewares:
        - add-iona-prefix
      service: thaumagen-github-io
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
    iona-thaumagen:
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/thaumagen`)
      entryPoints:
        - websecure
      middlewares:
        - add-iona-prefix
      service: thaumagen-github-io
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"

    iona-public:
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/public`)
      entryPoints:
        - websecure
      middlewares:
        - add-iona-prefix
      service: thaumagen-github-io
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"

    iona-static:
      entryPoints:
        - web
        - websecure
      rule: Host(`iona.thaumagen.io`) && PathPrefix(`/static`)
      service: nginx
      tls:
        certResolver: letsencrypt
        domains:
          - main: "thaumagen.io"
            sans: "*.thaumagen.io"
