http:

  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana.monitoring:80/

    nginx:
      loadBalancer:
        servers:
          - url: http://nginx.iona:80/

    thaumagen-github-io:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: https://thaumagen.github.io/
